[default]
static_dir = "./data/static"
static_zip_path = "./data/static.zip"
site_cache = true

[default.vcr]
tapes_folder = "./data/vhs_tapes"
feed_tape = "./data/vhs_tapes/feed.vhs"
site_tape = "./data/vhs_tapes/site_assets.vhs"
time_requests = true
check_site_tapes = false
