name: Build Voyager
on:
  push:
    branches:
      - main

env:
  vcr_commit: 605686a49690fecefe534efeeb6f5c0930fa1d8f
  rust_ver: "1.55"
  CARGO_PROFILE_RELEASE_LTO: fat
  CARGO_PROFILE_RELEASE_OPT_LEVEL: z
  RUSTFLAGS: -C target-feature=+crt-static
  VOYAGER_CROSS_HACK: 1

jobs:
  build-player-linux:
    name: Build player for Linux
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt-get install -y llvm-dev libclang-dev clang gcc-aarch64-linux-gnu
      - run: rustup install ${{ env.rust_ver }}
      - run: rustup target add aarch64-unknown-linux-gnu --toolchain ${{ env.rust_ver }}
      - uses: actions/checkout@v2
        with:
          repository: alisww/blaseball.vcr
          ref: ${{ env.vcr_commit }}
      - run: cargo +${{ env.rust_ver }} build --release -p player --features bundle_before --target x86_64-unknown-linux-gnu
      - run: cargo +${{ env.rust_ver }} build --release -p player --features bundle_before --target aarch64-unknown-linux-gnu
        env:
          BINDGEN_EXTRA_CLANG_ARGS: "--sysroot /usr/aarch64-linux-gnu"
      - run: strip target/x86_64-unknown-linux-gnu/release/player target/aarch64-unknown-linux-gnu/release/player
      - uses: actions/upload-artifact@v2
        with:
          name: player-linux
          path: |
            target/x86_64-unknown-linux-gnu/release/player
            target/aarch64-unknown-linux-gnu/release/player

  build-player-windows:
    name: Build player for Windows
    runs-on: windows-2019
    steps:
      - uses: KyleMayes/install-llvm-action@v1
        with:
          version: "12.0.1"
          directory: ${{ runner.temp }}/llvm
      - run: rustup install ${{ env.rust_ver }}
      - uses: actions/checkout@v2
        with:
          repository: alisww/blaseball.vcr
          ref: ${{ env.vcr_commit }}
      - run: cargo +${{ env.rust_ver }} build --release -p player --features bundle_before --target x86_64-pc-windows-msvc
      - uses: actions/upload-artifact@v2
        with:
          name: player-windows
          path: target/x86_64-pc-windows-msvc/release/player

  build-player-macos:
    name: Build player for macOS
    runs-on: macos-11
    steps:
      - run: rustup install ${{ env.rust_ver }}
      - run: rustup target add aarch64-apple-darwin --toolchain ${{ env.rust_ver }}
      - uses: actions/checkout@v2
        with:
          repository: alisww/blaseball.vcr
          ref: ${{ env.vcr_commit }}
      - run: cargo +${{ env.rust_ver }} build --release -p player --features bundle_before --target x86_64-apple-darwin
      - run: cargo +${{ env.rust_ver }} build --release -p player --features bundle_before --target aarch64-apple-darwin
      - run: strip target/x86_64-apple-darwin/release/player target/aarch64-apple-darwin/release/player
      - run: lipo -create -output target/x86_64-apple-darwin/release/player.lipo target/x86_64-apple-darwin/release/player target/aarch64-apple-darwin/release/player
      - uses: actions/upload-artifact@v2
        with:
          name: player-macos
          path: target/x86_64-apple-darwin/release/player.lipo
