name: TEST - Build Static Files
on:
  workflow_dispatch:  

env:
  RUST_VER: "1.70.0"
  VCR_COMMIT: 6896033eb5025027acaff85a78453a61b63edc5b
  TAPES_DIGEST: sha256:6444ab45689cbc92b8ab4b4504b6eb9a9523b9d809a0d13b9996e1a7a8d18d4e
  SIGILS_DIGEST: sha256:ac57e7acc0dd67a89ea3f889209dfdd20652243d1e2683b2781ecaae4dd95c78

jobs:
  build-static:
    name: Build static.zip and source.tar.zst
    runs-on: ubuntu-20.04
    steps:
      - run: rustup default ${{ env.RUST_VER }}
      - uses: actions/checkout@v2
        with:
          repository: emily-signet/blaseball.vcr
          ref: ${{ env.VCR_COMMIT }}
          fetch-depth: 0
      - uses: chetan/git-restore-mtime-action@v1
      - uses: Swatinem/rust-cache@v1
      - uses: actions/checkout@v2
        with:
          path: scripts
      - run: ./scripts/build-static.sh
      - uses: actions/upload-artifact@v2
        with:
          name: static-and-source
          path: |
            artifacts/static.zip
            artifacts/source.tar.xz
